"""add calls table

Revision ID: c443465f7a87
Revises: 8f51503007de
Create Date: 2026-07-30 06:49:43.705824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c443465f7a87'
down_revision: Union[str, None] = '8f51503007de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('caller_id', sa.UUID(), nullable=False),
    sa.Column('callee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RINGING', 'ONGOING', 'COMPLETED', 'MISSED', 'REJECTED', 'CANCELLED', name='call_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['callee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_callee_id'), 'calls', ['callee_id'], unique=False)
    op.create_index(op.f('ix_calls_caller_id'), 'calls', ['caller_id'], unique=False)
    op.create_index(op.f('ix_calls_conversation_id'), 'calls', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_conversation_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_caller_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_callee_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
